# Les clés API sont maintenant gérées via le fichier .env pour des raisons de sécurité
# Assurez-vous de configurer KRAKEN_API_KEY et KRAKEN_API_SECRET dans le fichier .env
trading:
  pairs:
  - XBT/USD
  - XBT/USDC
  - XBT/USDT
  - ETH/USD
  - ETH/USDT
  - ETH/USDC
  - XRP/USD
  - SOL/USD
  - ADA/USD
  - DOT/USD
  - LINK/USD
  - MATIC/USD
  - DOGE/USD
  - AVAX/USD
  - ATOM/USD
  - ALGO/USD
  - FIL/USD
  - LTC/USD
  - UNI/USD
  - AAVE/USD
  min_score: 0.3
  min_volume: 1000000
  risk_per_trade: 0.03  # 3% de risque par trade (équilibré pour 5 positions)
  stop_loss_percent: 0.03  # Stop-loss à 3% (ajusté pour le risque par trade)
  take_profit_percent: 0.06  # Take-profit à 6% (ratio 1:2)
  max_positions: 5  # Augmenté à 5 positions maximum
  max_drawdown: 0.15  # Drawdown maximum de 15% (ajusté pour plus de positions)
  max_holding_time: 86400
  max_concurrent_requests: 1
  analysis_timeout: 60.0
  max_pairs_to_analyze: 10
  cache_enabled: true
  cache_ttl: 3600
  exclude_illiquid: true
  min_daily_trades: 200
  min_market_cap: 100000000
  exclude_stablecoins: true
  exclude_leveraged: true
risk_management:
  risk_level: medium
  max_risk_per_trade: 0.02
  max_drawdown: 0.1
postgres:
  user: kraken_bot
  password: password
  host: localhost
  port: 5432
  database: kraken_bot
ml:
  window_size: 20
  train_size: 0.8
  n_estimators: 100
  max_depth: 10
log:
  log_dir: logs
  max_bytes: 10485760
  backup_count: 5
