kraken:
  api_key: MGvQ3MJ4Ya0yp/zI0k7ett8ug0mUP/3cRscuBBwckpWTGmDEu/qhPBge
  api_secret: 6y+hHCZ+YdwGck5Z4WtS8TJUa51ErvEx3E1k0OM24Bzr/tDHY4raO29ZhmCafcOoUUGXMEdvxjE8U5g/mbDvZw==
api_config:
  api_key: MGvQ3MJ4Ya0yp/zI0k7ett8ug0mUP/3cRscuBBwckpWTGmDEu/qhPBge
  api_secret: 6y+hHCZ+YdwGck5Z4WtS8TJUa51ErvEx3E1k0OM24Bzr/tDHY4raO29ZhmCafcOoUUGXMEdvxjE8U5g/mbDvZw==
trading:
  pairs:
  - 1INCHEUR
  - 1INCHUSD
  - AAVEETH
  - AAVEEUR
  - AAVEGBP
  - AAVEUSD
  - AAVEXBT
  - ACAEUR
  - ACAUSD
  - ACHEUR
  - ACHUSD
  - ACTEUR
  - ACTUSD
  - ACXEUR
  - ACXUSD
  - ADAAUD
  - ADAETH
  - ADAEUR
  - ADAGBP
  - ADAUSD
  - ADAUSDC
  - ADAUSDT
  - ADAXBT
  - ADXEUR
  - ADXUSD
  - AEROEUR
  - AEROUSD
  - AEVOEUR
  - AEVOUSD
  - AGLDEUR
  - AGLDUSD
  - AI16ZEUR
  - AI16ZUSD
  - AI16ZUSDC
  - AI16ZUSDT
  - AIOZEUR
  - AIOZUSD
  - AIREUR
  - AIRUSD
  - AIXBTEUR
  - AIXBTUSD
  - AKTEUR
  - AKTUSD
  - ALCHEUR
  - ALCHUSD
  - ALCXEUR
  - ALCXUSD
  - ALGOETH
  - ALGOEUR
  - ALGOGBP
  - ALGOUSD
  - ALGOUSDC
  - ALGOUSDT
  - ALGOXBT
  - ALICEEUR
  - ALICEUSD
  - ALPHAEUR
  - ALPHAUSD
  - ALTEUR
  - ALTUSD
  - ANKREUR
  - ANKRUSD
  - ANKRXBT
  - ANLOGEUR
  - ANLOGUSD
  - ANONEUR
  - ANONUSD
  - APEEUR
  - APENFTEUR
  - APENFTUSD
  - APEUSD
  - APEUSDC
  - APEUSDT
  - API3EUR
  - API3USD
  - APTEUR
  - APTUSD
  - APUEUR
  - APUUSD
  - ARBEUR
  - ARBUSD
  - ARCEUR
  - ARCUSD
  - AREUR
  - ARKMEUR
  - ARKMUSD
  - ARPAEUR
  - ARPAUSD
  - ARUSD
  - ASRREUR
  - ASRRUSD
  - ASTREUR
  - ASTRUSD
  - ATHEUR
  - ATHUSD
  - ATLASEUR
  - ATLASUSD
  - ATOMETH
  - ATOMEUR
  - ATOMGBP
  - ATOMUSD
  - ATOMUSDC
  - ATOMUSDT
  - ATOMXBT
  - AUCTIONEUR
  - AUCTIONUSD
  - AUDIOEUR
  - AUDIOUSD
  - AUDJPY
  - AUDUSD
  - AURAEUR
  - AURAUSD
  - AVAAIEUR
  - AVAAIUSD
  - AVAXEUR
  - AVAXUSD
  - AVAXUSDC
  - AVAXUSDT
  - AXSEUR
  - AXSUSD
  - B3EUR
  - B3USD
  - BABYEUR
  - BABYUSD
  - BADGEREUR
  - BADGERUSD
  - BALEUR
  - BALUSD
  - BANANAS31EUR
  - BANANAS31USD
  - BANDEUR
  - BANDUSD
  - BATEUR
  - BATUSD
  - BCHAUD
  - BCHETH
  - BCHEUR
  - BCHGBP
  - BCHJPY
  - BCHUSD
  - BCHUSDC
  - BCHUSDT
  - BCHXBT
  - BDXNEUR
  - BDXNUSD
  - BEAMEUR
  - BEAMUSD
  - BERAEUR
  - BERAUSD
  - BERAUSDC
  - BERAUSDT
  - BICOEUR
  - BICOUSD
  - BIGTIMEEUR
  - BIGTIMEUSD
  - BIOEUR
  - BIOUSD
  - BITEUR
  - BITUSD
  - BLUREUR
  - BLURUSD
  - BLZEUR
  - BLZUSD
  - BMTEUR
  - BMTUSD
  - BNBEUR
  - BNBUSD
  - BNBUSDC
  - BNBUSDT
  - BNCEUR
  - BNCUSD
  - BNTEUR
  - BNTUSD
  - BOBAEUR
  - BOBAUSD
  - BODENEUR
  - BODENUSD
  - BONDEUR
  - BONDUSD
  - BONKEUR
  - BONKUSD
  - BRICKEUR
  - BRICKUSD
  - BSXEUR
  - BSXUSD
  - BTTEUR
  - BTTUSD
  - C98EUR
  - C98USD
  - CAKEEUR
  - CAKEUSD
  - CATEUR
  - CATUSD
  - CELOEUR
  - CELOUSD
  - CELREUR
  - CELRUSD
  - CFGEUR
  - CFGUSD
  - CHEEMSEUR
  - CHEEMSUSD
  - CHEXEUR
  - CHEXUSD
  - CHILLHOUSEEUR
  - CHILLHOUSEUSD
  - CHREUR
  - CHRUSD
  - CHZEUR
  - CHZUSD
  - CLANKEREUR
  - CLANKERUSD
  - CLOUDEUR
  - CLOUDUSD
  - CLVEUR
  - CLVUSD
  - CMETHETH
  - CMETHUSD
  - COMPEUR
  - COMPUSD
  - COMPXBT
  - COOKIEEUR
  - COOKIEUSD
  - COQEUR
  - COQUSD
  - CORNEUR
  - CORNUSD
  - COTIEUR
  - COTIUSD
  - COWEUR
  - COWUSD
  - CPOOLEUR
  - CPOOLUSD
  - CQTEUR
  - CQTUSD
  - CROEUR
  - CROUSD
  - CROUSDC
  - CROUSDT
  - CRVEUR
  - CRVUSD
  - CSMEUR
  - CSMUSD
  - CTSIEUR
  - CTSIUSD
  - CVCEUR
  - CVCUSD
  - CVXEUR
  - CVXUSD
  - CXTEUR
  - CXTUSD
  - CYBEREUR
  - CYBERUSD
  - DAIEUR
  - DAIUSD
  - DAIUSDT
  - DASHEUR
  - DASHUSD
  - DBREUR
  - DBRUSD
  - DEEPEUR
  - DEEPUSD
  - DEGENEUR
  - DEGENUSD
  - DENTEUR
  - DENTUSD
  - DMCEUR
  - DMCUSD
  - DOGEUR
  - DOGSEUR
  - DOGSUSD
  - DOGUSD
  - DOLOEUR
  - DOLOUSD
  - DOTETH
  - DOTEUR
  - DOTGBP
  - DOTJPY
  - DOTUSD
  - DOTUSDC
  - DOTUSDT
  - DOTXBT
  - DRIFTEUR
  - DRIFTUSD
  - DRVEUR
  - DRVUSD
  - DUCKEUR
  - DUCKUSD
  - DYDXEUR
  - DYDXUSD
  - DYMEUR
  - DYMUSD
  - EDGEEUR
  - EDGEUSD
  - EGLDEUR
  - EGLDUSD
  - EIGENEUR
  - EIGENUSD
  - ELXEUR
  - ELXUSD
  - ENAEUR
  - ENAUSD
  - ENJEUR
  - ENJUSD
  - ENSEUR
  - ENSUSD
  - EPTEUR
  - EPTUSD
  - ESEUR
  - ESUSD
  - ESXEUR
  - ESXUSD
  - ETHAUD
  - ETHCHF
  - ETHDAI
  - ETHFIEUR
  - ETHFIUSD
  - ETHPYUSD
  - ETHUSDC
  - ETHUSDT
  - ETHWETH
  - ETHWEUR
  - ETHWUSD
  - EULEUR
  - EULUSD
  - EURAUD
  - EURCAD
  - EURCHF
  - EURGBP
  - EURJPY
  - EUROPEUR
  - EUROPUSD
  - EUROPUSDC
  - EURQEUR
  - EURQUSD
  - EURREUR
  - EURRUSD
  - EURRUSDC
  - EURRUSDT
  - EWTEUR
  - EWTUSD
  - FARMEUR
  - FARMUSD
  - FARTCOINEUR
  - FARTCOINUSD
  - FARTCOINUSDC
  - FARTCOINUSDT
  - FETEUR
  - FETUSD
  - FHEEUR
  - FHEUSD
  - FIDAEUR
  - FIDAUSD
  - FILETH
  - FILEUR
  - FILGBP
  - FILUSD
  - FILXBT
  - FISEUR
  - FISUSD
  - FLOKIEUR
  - FLOKIUSD
  - FLOWEUR
  - FLOWUSD
  - FLREUR
  - FLRUSD
  - FLUXEUR
  - FLUXUSD
  - FLYEUR
  - FLYUSD
  - FORTHEUR
  - FORTHUSD
  - FWOGEUR
  - FWOGUSD
  - FXSEUR
  - FXSUSD
  - GALAEUR
  - GALAUSD
  - GALEUR
  - GALUSD
  - GARIEUR
  - GARIUSD
  - GEUR
  - GFIEUR
  - GFIUSD
  - GHIBLIEUR
  - GHIBLIUSD
  - GHSTEUR
  - GHSTUSD
  - GIGAEUR
  - GIGAUSD
  - GLMREUR
  - GLMRUSD
  - GMTEUR
  - GMTUSD
  - GMXEUR
  - GMXUSD
  - GNOEUR
  - GNOUSD
  - GOATEUR
  - GOATUSD
  - GOMININGEUR
  - GOMININGUSD
  - GRASSEUR
  - GRASSUSD
  - GRIFFAINEUR
  - GRIFFAINUSD
  - GRTEUR
  - GRTGBP
  - GRTUSD
  - GRTXBT
  - GSTEUR
  - GSTUSD
  - GTCEUR
  - GTCUSD
  - GUNEUR
  - GUNUSD
  - GUSD
  - HBAREUR
  - HBARUSD
  - HDXEUR
  - HDXUSD
  - HFTEUR
  - HFTUSD
  - HIPPOEUR
  - HIPPOUSD
  - HMSTREUR
  - HMSTRUSD
  - HNTEUR
  - HNTUSD
  - HONEYEUR
  - HONEYUSD
  - HPOS10IEUR
  - HPOS10IUSD
  - ICNTEUR
  - ICNTUSD
  - ICPEUR
  - ICPUSD
  - ICXEUR
  - ICXUSD
  - IDEXEUR
  - IDEXUSD
  - IMXEUR
  - IMXUSD
  - INITEUR
  - INITUSD
  - INJEUR
  - INJUSD
  - INTREUR
  - INTRUSD
  - IPEUR
  - IPUSD
  - JAILSTOOLEUR
  - JAILSTOOLUSD
  - JASMYEUR
  - JASMYUSD
  - JITOSOLEUR
  - JITOSOLSOL
  - JITOSOLUSD
  - JOEEUR
  - JOEUSD
  - JSTEUR
  - JSTUSD
  - JTOEUR
  - JTOUSD
  - JUNOEUR
  - JUNOUSD
  - JUPEUR
  - JUPUSD
  - KAITOEUR
  - KAITOUSD
  - KAREUR
  - KARUSD
  - KASEUR
  - KASUSD
  - KAVAEUR
  - KAVAUSD
  - KEEPEUR
  - KEEPUSD
  - KERNELEUR
  - KERNELUSD
  - KETEUR
  - KETUSD
  - KEYEUR
  - KEYUSD
  - KINEUR
  - KINTEUR
  - KINTUSD
  - KINUSD
  - KMNOEUR
  - KMNOUSD
  - KNCEUR
  - KNCUSD
  - KOBANEUR
  - KOBANUSD
  - KP3REUR
  - KP3RUSD
  - KSMEUR
  - KSMGBP
  - KSMUSD
  - L3EUR
  - L3USD
  - LAYEREUR
  - LAYERUSD
  - LCXEUR
  - LCXUSD
  - LDOEUR
  - LDOUSD
  - LINKAUD
  - LINKETH
  - LINKEUR
  - LINKGBP
  - LINKJPY
  - LINKUSD
  - LINKUSDC
  - LINKUSDT
  - LINKXBT
  - LITEUR
  - LITUSD
  - LMWREUR
  - LMWRUSD
  - LOCKINEUR
  - LOCKINUSD
  - LOFIEUR
  - LOFIUSD
  - LPTEUR
  - LPTUSD
  - LQTYEUR
  - LQTYUSD
  - LRCEUR
  - LRCUSD
  - LSETHETH
  - LSETHEUR
  - LSETHUSD
  - LSKEUR
  - LSKUSD
  - LSSOLEUR
  - LSSOLSOL
  - LSSOLUSD
  - LTCAUD
  - LTCETH
  - LTCGBP
  - LTCUSDC
  - LTCUSDT
  - LUNA2EUR
  - LUNA2USD
  - LUNAEUR
  - LUNAUSD
  - MANAEUR
  - MANAUSD
  - MANAUSDC
  - MANAUSDT
  - MANAXBT
  - MASKEUR
  - MASKUSD
  - MATEUR
  - MATUSD
  - MCEUR
  - MCUSD
  - MEEUR
  - MELANIAEUR
  - MELANIAUSD
  - MELANIAUSDC
  - MELANIAUSDT
  - MEMEEUR
  - MEMEUSD
  - MERLEUR
  - MERLUSD
  - METHETH
  - METHUSD
  - METISEUR
  - METISUSD
  - MEUR
  - MEUSD
  - MEWEUR
  - MEWUSD
  - MICHIEUR
  - MICHIUSD
  - MINAEUR
  - MINAGBP
  - MINAUSD
  - MINAXBT
  - MIREUR
  - MIRUSD
  - MKREUR
  - MKRUSD
  - MKRXBT
  - MNGOEUR
  - MNGOUSD
  - MNTEUR
  - MNTUSD
  - MOGEUR
  - MOGUSD
  - MOODENGEUR
  - MOODENGUSD
  - MOONEUR
  - MOONUSD
  - MORPHOEUR
  - MORPHOUSD
  - MOVEEUR
  - MOVEUSD
  - MOVREUR
  - MOVRUSD
  - MSOLEUR
  - MSOLUSD
  - MUBARAKEUR
  - MUBARAKUSD
  - MULTIEUR
  - MULTIUSD
  - MUSD
  - MVEUR
  - MVUSD
  - MXCEUR
  - MXCUSD
  - NANOEUR
  - NANOUSD
  - NEAREUR
  - NEARUSD
  - NEIROEUR
  - NEIROUSD
  - NILEUR
  - NILUSD
  - NMREUR
  - NMRUSD
  - NODLEUR
  - NODLUSD
  - NOSEUR
  - NOSUSD
  - NOTEUR
  - NOTUSD
  - NPCEUR
  - NPCUSD
  - NTRNEUR
  - NTRNUSD
  - NYMEUR
  - NYMUSD
  - OCEANEUR
  - OCEANUSD
  - ODOSEUR
  - ODOSUSD
  - OGNEUR
  - OGNUSD
  - OMEUR
  - OMGEUR
  - OMGUSD
  - OMNIEUR
  - OMNIUSD
  - OMUSD
  - ONDOEUR
  - ONDOUSD
  - OPEUR
  - OPUSD
  - ORCAEUR
  - ORCAUSD
  - ORDEREUR
  - ORDERUSD
  - OSMOEUR
  - OSMOUSD
  - OXTEUR
  - OXTUSD
  - OXYEUR
  - OXYUSD
  - PARTIEUR
  - PARTIUSD
  - PAXGETH
  - PAXGEUR
  - PAXGUSD
  - PAXGXBT
  - PDAEUR
  - PDAUSD
  - PEAQEUR
  - PEAQUSD
  - PENDLEEUR
  - PENDLEUSD
  - PENGUEUR
  - PENGUUSD
  - PENGUUSDC
  - PENGUUSDT
  - PEPEAUD
  - PEPECAD
  - PEPEEUR
  - PEPEGBP
  - PEPEUSD
  - PERPEUR
  - PERPUSD
  - PHAEUR
  - PHAUSD
  - PLUMEEUR
  - PLUMEUSD
  - PNUTEUR
  - PNUTUSD
  - POLEUR
  - POLISEUR
  - POLISUSD
  - POLSEUR
  - POLSUSD
  - POLUSD
  - PONDEUR
  - PONDUSD
  - PONKEEUR
  - PONKEUSD
  - POPCATEUR
  - POPCATGBP
  - POPCATUSD
  - PORTALEUR
  - PORTALUSD
  - POWREUR
  - POWRUSD
  - PRCLEUR
  - PRCLUSD
  - PRIMEEUR
  - PRIMEUSD
  - PROEUR
  - PROMPTEUR
  - PROMPTUSD
  - PROUSD
  - PSTAKEEUR
  - PSTAKEUSD
  - PUFFEREUR
  - PUFFERUSD
  - PUMPEUR
  - PUMPSOL
  - PUMPUSD
  - PYTHEUR
  - PYTHUSD
  - PYUSDEUR
  - PYUSDUSD
  - QIEUR
  - QIUSD
  - QNTEUR
  - QNTUSD
  - QTUMEUR
  - QTUMUSD
  - RADEUR
  - RADUSD
  - RAIINEUR
  - RAIINUSD
  - RAREEUR
  - RAREUSD
  - RARIEUR
  - RARIUSD
  - RAYEUR
  - RAYUSD
  - RBCEUR
  - RBCUSD
  - REDEUR
  - REDUSD
  - RENDEREUR
  - RENDERUSD
  - RENEUR
  - RENUSD
  - REPV2EUR
  - REPV2USD
  - REQEUR
  - REQUSD
  - REZEUR
  - REZUSD
  - RIZEEUR
  - RIZEUSD
  - RLCEUR
  - RLCUSD
  - RLUSDEUR
  - RLUSDUSD
  - RLUSDUSDC
  - RLUSDUSDT
  - ROOKEUR
  - ROOKUSD
  - RPLEUR
  - RPLUSD
  - RSREUR
  - RSRUSD
  - RUJIEUR
  - RUJIUSD
  - RUNEEUR
  - RUNEUSD
  - SAFEEUR
  - SAFEUSD
  - SAGAEUR
  - SAGAUSD
  - SAHARAEUR
  - SAHARAUSD
  - SAMOEUR
  - SAMOUSD
  - SANDEUR
  - SANDGBP
  - SANDUSD
  - SANDXBT
  - SBREUR
  - SBRUSD
  - SCEUR
  - SCRTEUR
  - SCRTUSD
  - SCUSD
  - SCXBT
  - SDNEUR
  - SDNUSD
  - SEIEUR
  - SEIUSD
  - SEUR
  - SGBEUR
  - SGBUSD
  - SHIBEUR
  - SHIBUSD
  - SHIBUSDC
  - SHIBUSDT
  - SIGMAEUR
  - SIGMAUSD
  - SKYEUR
  - SKYUSD
  - SNEKEUR
  - SNEKUSD
  - SNXEUR
  - SNXUSD
  - SNXXBT
  - SOGNIEUR
  - SOGNIUSD
  - SOLAUD
  - SOLCAD
  - SOLETH
  - SOLEUR
  - SOLGBP
  - SOLUSD
  - SOLUSDC
  - SOLUSDT
  - SOLXBT
  - SONICEUR
  - SONICUSD
  - SOSOEUR
  - SOSOUSD
  - SPELLEUR
  - SPELLUSD
  - SPICEEUR
  - SPICEUSD
  - SPKEUR
  - SPKUSD
  - SPXEUR
  - SPXUSD
  - SRMEUR
  - SRMUSD
  - SSVEUR
  - SSVUSD
  - STEPEUR
  - STEPUSD
  - STGEUR
  - STGUSD
  - STORJEUR
  - STORJUSD
  - STRDEUR
  - STRDUSD
  - STRKEUR
  - STRKUSD
  - STXEUR
  - STXUSD
  - SUIEUR
  - SUIGBP
  - SUIUSD
  - SUNDOGEUR
  - SUNDOGUSD
  - SUNEUR
  - SUNUSD
  - SUPEREUR
  - SUPERUSD
  - SUSD
  - SUSDC
  - SUSDT
  - SUSHIEUR
  - SUSHIUSD
  - SWARMSEUR
  - SWARMSUSD
  - SWEATEUR
  - SWEATUSD
  - SWELLEUR
  - SWELLUSD
  - SXTEUR
  - SXTUSD
  - SYNEUR
  - SYNUSD
  - SYRUPEUR
  - SYRUPUSD
  - TACEUR
  - TACUSD
  - TANSSIEUR
  - TANSSIUSD
  - TAOEUR
  - TAOUSD
  - TBTCEUR
  - TBTCUSD
  - TBTCXBT
  - TEEREUR
  - TEERUSD
  - TERMEUR
  - TERMUSD
  - TEUR
  - TIAEUR
  - TIAUSD
  - TITCOINEUR
  - TITCOINUSD
  - TLMEUR
  - TLMUSD
  - TNSREUR
  - TNSRUSD
  - TOKEEUR
  - TOKENEUR
  - TOKENUSD
  - TOKEUSD
  - TONEUR
  - TONUSD
  - TONUSDC
  - TONUSDT
  - TOSHIEUR
  - TOSHIUSD
  - TRACEUR
  - TRACUSD
  - TREEEUR
  - TREEUSD
  - TREMPEUR
  - TREMPUSD
  - TRUEUR
  - TRUMPEUR
  - TRUMPUSD
  - TRUMPUSDC
  - TRUMPUSDT
  - TRUUSD
  - TRXETH
  - TRXEUR
  - TRXUSD
  - TRXUSDD
  - TRXXBT
  - TURBOEUR
  - TURBOUSD
  - TUSD
  - TUSDEUR
  - TUSDUSD
  - TVKEUR
  - TVKUSD
  - UFDEUR
  - UFDUSD
  - UMAEUR
  - UMAUSD
  - UNFIEUR
  - UNFIUSD
  - UNIETH
  - UNIEUR
  - UNIUSD
  - UNIXBT
  - USDCAUD
  - USDCCAD
  - USDCCHF
  - USDCEUR
  - USDCGBP
  - USDCHF
  - USDCUSD
  - USDCUSDT
  - USDDEUR
  - USDDUSD
  - USDGEUR
  - USDGUSD
  - USDGUSDC
  - USDQEUR
  - USDQUSD
  - USDQUSDC
  - USDQUSDT
  - USDREUR
  - USDRUSD
  - USDRUSDC
  - USDRUSDT
  - USDSEUR
  - USDSUSD
  - USDTAUD
  - USDTCAD
  - USDTCHF
  - USDTEUR
  - USDTGBP
  - USDTJPY
  - USDTZUSD
  - USDUCEUR
  - USDUCUSD
  - USTEUR
  - USTUSD
  - USTUSDC
  - USTUSDT
  - USUALEUR
  - USUALUSD
  - VANRYEUR
  - VANRYUSD
  - VELODROMEEUR
  - VELODROMEUSD
  - VINEEUR
  - VINEUSD
  - VIRTUALEUR
  - VIRTUALUSD
  - VIRTUALUSDC
  - VIRTUALUSDT
  - VSNEUR
  - VSNUSD
  - VVVEUR
  - VVVUSD
  - WALEUR
  - WALUSD
  - WAXLEUR
  - WAXLUSD
  - WBTCEUR
  - WBTCUSD
  - WBTCXBT
  - WCTEUR
  - WCTUSD
  - WELLEUR
  - WELLUSD
  - WENEUR
  - WENUSD
  - WEUR
  - WIFEUR
  - WIFGBP
  - WIFUSD
  - WINEUR
  - WINUSD
  - WLDEUR
  - WLDUSD
  - WOOEUR
  - WOOUSD
  - WUSD
  - XBTAUD
  - XBTCHF
  - XBTDAI
  - XBTPYUSD
  - XBTUSDC
  - XBTUSDT
  - XCNEUR
  - XCNUSD
  - XDGAUD
  - XDGCAD
  - XDGEUR
  - XDGGBP
  - XDGUSD
  - XDGUSDC
  - XDGUSDT
  - XETCXETH
  - XETCXXBT
  - XETCZEUR
  - XETCZUSD
  - XETHXXBT
  - XETHZCAD
  - XETHZEUR
  - XETHZGBP
  - XETHZJPY
  - XETHZUSD
  - XLTCXXBT
  - XLTCZEUR
  - XLTCZJPY
  - XLTCZUSD
  - XMLNXXBT
  - XMLNZEUR
  - XMLNZUSD
  - XMRUSDC
  - XMRUSDT
  - XREPZEUR
  - XREPZUSD
  - XRPAUD
  - XRPETH
  - XRPGBP
  - XRPRLUSD
  - XRPUSDC
  - XRPUSDT
  - XRTEUR
  - XRTUSD
  - XTZEUR
  - XTZUSD
  - XTZUSDC
  - XTZUSDT
  - XXBTUSDQ
  - XXBTUSDR
  - XXBTZCAD
  - XXBTZEUR
  - XXBTZGBP
  - XXBTZJPY
  - XXBTZUSD
  - XXDGXXBT
  - XXLMXXBT
  - XXLMZEUR
  - XXLMZGBP
  - XXLMZUSD
  - XXMRXXBT
  - XXMRZEUR
  - XXMRZUSD
  - XXRPXXBT
  - XXRPZCAD
  - XXRPZEUR
  - XXRPZUSD
  - XZECZEUR
  - XZECZUSD
  - YFIEUR
  - YFIUSD
  - YGGEUR
  - YGGUSD
  - ZEREBROEUR
  - ZEREBROUSD
  - ZETAEUR
  - ZETAUSD
  - ZEURZUSD
  - ZEUSEUR
  - ZEUSUSD
  - ZEXEUR
  - ZEXUSD
  - ZGBPZUSD
  - ZKEUR
  - ZKUSD
  - ZORAEUR
  - ZORAUSD
  - ZROEUR
  - ZROUSD
  - ZRXEUR
  - ZRXUSD
  - ZRXXBT
  - ZUSDZCAD
  - ZUSDZJPY
  min_score: 0.05
  min_volume: 100000
  risk_per_trade: 0.02
  stop_loss_percent: 0.02
  take_profit_percent: 0.04
  max_positions: 5
  max_drawdown: 0.1
  max_holding_time: 86400
risk_management:
  max_risk_per_trade: 0.02
  max_drawdown: 0.1
postgres:
  user: kraken_bot
  password: password
  host: localhost
  port: 5432
  database: kraken_bot
ml:
  window_size: 20
  train_size: 0.8
  n_estimators: 100
  max_depth: 10
log:
  log_dir: logs
  max_bytes: 10485760
  backup_count: 5
